name: Main

on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Workflow is running
        run: |
          echo "Hello from GitHub actions"
          echo ${{ github.event_name }}

      - name: Run if workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo Workflow has been dispatched

      - name: Run if push
        if: github.event_name == 'push'
        run: echo Something has been pushed

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get version
        run: |
          echo ::set-env name=POM_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo version: ${{ env.POM_VERSION }}
        id: get_version
