name: Main

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Workflow is running
        run: |
          echo "Hello from GitHub actions"
          echo ${{ github.event_name }}
